### ISSUE TITLE
Consider inlining Newtonsoft for JSON Serialization

### ISSUE THREAD

**Issue by glatzert** [PKISharp/ACMESharpCore-PowerShell#1]
I serialized the ServiceDirectory manually now, but I don't know, if that's good to Keep here.
I'm considering pulling Newtonsofts.JSON for Deserializing the JSON directly into the types.
Essentially the conversion should work oobe, but it didn't in practice...

**Comment by glatzert** [comment]
Using own Classes for Return types - so Closing this again

**Comment by ebekker** [comment]
I guess one approach might be some sort of intermediate translator that is aware of all the core entities, but then can transform them or just de/serialize them from/to whatever backend storage is used.

For example, for just files or even a JSON document store, you would use a JSON serializer (like Netwonsoft or JsonUtil) but perhaps if you use a RDMBS store, it would translate using some ORM technology like EF or dapper.

HOWEVER, I think with the current protocol client, that concern sits at a higher level and can be deferred to the client implementation, such as this PWSH module.  After some experience and feedback, we may be able to come up with a more generalized set of tools and abstractions that can be shared by all clients.
