### ISSUE TITLE
Allow Settings for CSR and CertificateExport

### ISSUE THREAD

**Issue by glatzert** [PKISharp/ACMESharpCore-PowerShell#18]
Currently the module picks the CN of the certificate from the DNS name list.
Since Update-Order will normally be called before Complete-Order the list is updated from the ACME service, which orders the identifiers by name. Thus the CN will always be the first identifier in alphabetical order.

This Issue is to discuss:
 - approaches to allow modifying the CSR
 - listing other usages of Certificate(Request)Settings, which could be added to an order object.

#17 seems to be an valid approach, but could be refined to allow covering a broader set of use cases.

**Comment by glatzert** [comment]
- [ ] Identify options, which can be set in ACME services (or LE specific)
- [ ] Define settings, which should be changeable
- [ ] Define, if we need CSRSettings AND CertificateExportSettings or one set (if this apporach will work)
- [ ] Decide how to associate the Settings with an AcmeOrder

**Comment by glatzert** [comment]
As of now, I could only identify two settable things - CN for the CSR and FriendlyName for Export. The latter one might be windows only. Do you know more @casselc ?

**Comment by j81blog** [comment]
Is there an estimate for this feature? Would like the option to define the Common Name of the certificate (or the first of the identifiers list as Common Name) now it's the first in the list as returned by Let's Encrypt. If I want a cert for domain.com and *.domain.com, I would like domain.com to be the Common Name and *.domain.com in the SAN area. Currently the *.domain will be the common name of the certificate.

**Comment by glatzert** [comment]
I decided to allow setting the CertDN during New-Order or just going with the first Identifier you provide as DN.
I'll upload is as 1.0.5-beta1 and as soon as I tested it in my environment, I'll remove the prerelease tag.
