### ISSUE TITLE
Update Get-Authorization.ps1 to support POST AS Get Request

### ISSUE THREAD

**Issue by san360** [PKISharp/ACMESharpCore-PowerShell#25]
As per the new acme draft version the methods should support GET AS POST request instead of GET request. I updated the Get Authorization method below and tested it. Please incorporate it into the client 

--- a/ACME-PS/functions/Authorization/Get-Authorization.ps1
+++ b/ACME-PS/functions/Authorization/Get-Authorization.ps1
@@ -30,16 +30,26 @@ function Get-Authorization {
         [Parameter(Mandatory = $true, Position = 0, ParameterSetName = "FromUrl")]
         [ValidateNotNullOrEmpty()]
         [uri]
-        $Url
+        $Url,
+
+        [Parameter(Mandatory = $true, Position = 0)]
+        [ValidateNotNull()]
+        [ValidateScript({$_.Validate()})]
+        [AcmeState]
+        $State
     )

     process {
+        $payload = @{};
         switch ($PSCmdlet.ParameterSetName) {
             "FromOrder" {
-                $Order.AuthorizationUrls | ForEach-Object { Get-Authorization -Url $_ }
+                $Order.AuthorizationUrls | ForEach-Object { Get-Authorization -Url $_ $State }
             }
             Default {
-                $response = Invoke-AcmeWebRequest $Url -Method GET;
+                #$response = Invoke-AcmeWebRequest $Url -Method POST;
+                $response = Invoke-SignedWebRequest $Url $State $payload;
+
                 return [AcmeAuthorization]::new($response);
             }
         }

**Comment by glatzert** [comment]
If you already have a implementation, feel free to make a create a proper PullRequest.
Else, I'm gonna check the RFC, and adjust all functions as neccessary.

I'm tracking the Issue in #26
