### ISSUE TITLE
Support POST-as-GET Requests, where indicated by RFC 8555

### ISSUE THREAD

**Issue by glatzert** [PKISharp/ACMESharpCore-PowerShell#26]
ACMEs RFC (https://tools.ietf.org/html/rfc8555#section-6.3 and following) defines some of the requests to be POST-as-GET.
We do not adhere to that everywhere and have to adjust to be compliant.

The CmdLets will be examined and corrected where neccessary.

**Comment by san360** [comment]
FYI, Based on https://github.com/letsencrypt/boulder/blob/master/docs/acme-divergences.md

_POST-as-GET: We support POST-as-GET but do not yet mandate it. We plan to mandate POST-as-GET for all ACMEv2 requests in late 2019._

**Comment by glatzert** [comment]
Closed via #37
