### ISSUE TITLE
Export-Certificate not supported in PowerShell 6

### ISSUE THREAD

**Issue by hoppyluke** [PKISharp/ACMESharpCore-PowerShell#28]
`Export-Certificate` uses `Set-Content -Encoding byte` to save the certificate.

There was a [breaking change in PowerShell 6.0](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/breaking-changes-ps6?view=powershell-6#unify-cmdlets-with-parameter--encoding-to-be-of-type-systemtextencoding-5080) that drops the `byte` encoding. PS 6 requires a new `-AsByteStream` switch instead.

**Comment by glatzert** [comment]
Well, that is most unfortunate - that means there's probably some switch and bait for the Windows PS vs PS Core neccessary now.

I'll take a look into it this weekend. Thanks for pointing out.

**Comment by glatzert** [comment]
I implemented a simple code branch by PSVersion, which should solve the problem.
I'd really be thankful, if you or someone would have the time to validate the new beta module, since I will not be able until end of the week.

**Comment by hoppyluke** [comment]
:+1: Thanks - I've tested `1.0.7-beta` in PowerShell 5 and 6 and it's working in both.
