### ISSUE TITLE
How to use ACME-PS with SANs

### ISSUE THREAD

**Issue by zoTT5301** [PKISharp/ACMESharpCore-PowerShell#34]
Hi,
please help.
I have tried to supply an array [AcmeIdentifier[]] for the New-ACMEOrder
 that sows an error in the next function:  Get-ACMEAuthorization

<code>
    # Create the identifier for the DNS name
    $ACMEIdentifierCN = New-ACMEIdentifier $LECERT_ServerCN;

    # Build Identifier-Array
    [AcmeIdentifier[]] $ACMEIdentifiers = $NULL;
    $ACMEIdentifiers +=$ACMEIdentifierCN;

    #Add SANs
    foreach ($SAN in $LECERT_SANs)
    {
          $ACMEIdentifiers += New-ACMEIdentifier $SAN
    }

    # Create the order object at the ACME service.
    $ACMEOrder = New-ACMEOrder $ACMEState  -Identifiers $ACMEIdentifiers;

    # Fetch the authorizations for that order
    $ACMEauthZ = Get-ACMEAuthorization  -Order $ACMEOrder;

</code>

Error:
-> The type System.Object[]  cannot converted into type AcmeAuthorization
original (in german)
Get-ACMEChallenge : Die Argumenttransformation für den Parameter "Authorization" kann nicht verarbeitet werden. Der Wert "System.Object[]" vom Typ "System.Object[]" kann nicht in den Typ "AcmeAuthorization" konvertiert werden.

is there some problem if the identifier is not even a single value?
how does it work to get a certificate with more than one name (SANs)?

**Comment by glatzert** [comment]
To be true, I think I never tried SAN, since we (University of Mainz in this case) are not using any. IIS with centralized certificate store does not work with a SANs, so our main use case did not require it (essentially it works, but is of little use).

Nevertheless it's a valid issue, that this won't work.
If you have the time, feel free to provide a fix, I'll happily deploy a next version. If not you probably need to wait until mid to late August, until I find the time to fix it and make the newer get-as-post available as well.

**Comment by glatzert** [comment]
Can you tell me, what line of your code throws the exception?

The error message says it's part of Get-ACMEChallenge, which is never called from the module itself, so it seems the error comes later?

**Comment by zoTT5301** [comment]
First of all my script begins with 
using module  ACME-PS

That offers the type "AcmeIdentifier" and is the only way to call the  New-ACMEOrder type-conform with an AcmeIdentifier[] array.

    # Build the array
    [AcmeIdentifier[]] $ACMEIdentifiers = $NULL;
    $ACMEIdentifiers +=$ACMEServerCN;

    #Add SANs from a SAN string-array
    foreach ($SAN in $LECERT_SANs) 
    {
          $ACMEIdentifiers += New-ACMEIdentifier $SAN
    }

    # Create the order object at the ACME service.
    $ACMEOrder = New-ACMEOrder $ACMEState  -Identifiers $ACMEIdentifiers;

    # Fetch the authorizations for that order
    $ACMEauthZ = Get-ACMEAuthorization  -Order $ACMEOrder;

    # Select a challenge to fullfill
    $ACMEChallenge = Get-ACMEChallenge $ACMEState $ACMEauthZ "http-01";

and here occurs the exception: Get-ACMEChallenge

That was my approach to place an order more than one Name for the Certificate.

I am also not sure how to get a wildcard-Certificate...

**Comment by glatzert** [comment]
Get-ACMEAuthorizations might return multiple authorizations for SAN.
`foreach($authz in $acmeAuthz) {...}` might solve your problem.

**Comment by glatzert** [comment]
Since I did not hear back anything by now, I'm closing this as done.

**Comment by asifma** [comment]
This works, just pipe it...:

`$ACMEChallenge = $ACMEauthZ | Get-ACMEChallenge -State $ACMEState -Type "dns-01"`
