### ISSUE TITLE
Deploy the latest version to PSGallery

### ISSUE THREAD

**Issue by DOMZE** [PKISharp/ACMESharpCore-PowerShell#38]
Hey!

Thank you for this library. Very useful. Just a quick note to say that 1.1.0 is not published on PSGallery.

Also do you think your library could support account deactivation? see https://tools.ietf.org/html/draft-ietf-acme-acme-09#section-7.3.7

Thank you

**Comment by glatzert** [comment]
Hi, I deployed 1.1.0 without the prerelease tag, since it's now "battle tested" at my employer.

Also I opened#39 for your suggestion.
