### ISSUE TITLE
Status: Invalid error

### ISSUE THREAD

**Issue by nikydobrev** [PKISharp/ACMESharpCore-PowerShell#43]
Hello,

First of all I wanted to express my appreciation for this Powershell module that support Acme v,2 protocol. Really great work. It was working perfectly till today.. 

I managed to issue certificates for may domains, but today when script was running I get the Status: **Invalid**

I have deleted AcmeState folder and tried to rerun the script, same error. Also Absolute Url is available and can be requested.

Thanks in advance for the help.

[logs.txt](https://github.com/PKISharp/ACMESharpCore-PowerShell/files/3840205/logs.txt)
[AcmeState.zip](https://github.com/PKISharp/ACMESharpCore-PowerShell/files/3840209/AcmeState.zip)

**Comment by glatzert** [comment]
If I try to read http://dev2.sitefinity.cloud/.well-known/acme-challenge/OdJmofE7rCKresxxjvCDgPoZfKMMzXL0gwsTAck97F4 (which should be the challange URL), I don't get an answer.
Might this be something only reachable internally?

**Comment by nikydobrev** [comment]
It was a network restrictions on my end. Issue is resolved and the script works like a charm :)

**Comment by glatzert** [comment]
Happy to help
