### ISSUE TITLE
Multiple DNS Certificate Example

### ISSUE THREAD

**Issue by kiwiingenuity** [PKISharp/ACMESharpCore-PowerShell#53]
Is there an example or can you expand on the sample in the Readme document for creating a certificate or 2 dns names?  e.g.   example.com & www.example.com

**Comment by glatzert** [comment]
Just create an array of Identifiers. e.g `@("www.example.com", "example.com") | % { New-AcmeIdentifier $_ }`. Be aware, that this might lead to mutliple authorizations beeing returned for a single order.

I plan on providing a folder of samples, with different use cases.

**Comment by GeorgeSchiro** [comment]
@kiwiingenuity, "GetCert2" is a full working example (with simple GUI) of multiple SAN support in "ACME-PS". Let me know if you would like more details.

**Comment by kiwiingenuity** [comment]
@glatzert You are correct that I received Multiple authorizations, at which point I did not know what to do?
Can you please advise or better still add the solution to a Samples folder.

**Comment by glatzert** [comment]
Essentially you need to foreach over the authorizations and fullfil one challange foreach one.
I'll create a samples folder, but that'll take some time.

**Comment by glatzert** [comment]
Created #55 to collect sample ideas
