### ISSUE TITLE
Leaking AcmeState

### ISSUE THREAD

**Issue by GeorgeSchiro** [PKISharp/ACMESharpCore-PowerShell#54]
First, the new "stateless" features (which are really "stateful" - ie. session independent, see #46) are working great! Thank you Thomas.

I've completed most of my testing and noticed only one issue: new state is not limited to the "{path to AcmeState}" folder (where "{path to AcmeState}" is the path given to "New-ACMEState"). 

New state items are appearing in the parent folder of "{path to AcmeState}":

    "{path to AcmeState}Orders\"
    "{path to AcmeState}Account.xml"
    "{path to AcmeState}AccountKey.xml"

Can you move the new state to the "{path to AcmeState}" folder?

**Comment by glatzert** [comment]
There's a small error in the AcmeState, but I could not push it yesterday evening, since my ISP stopped me. I'll have it pushed this evening

**Comment by glatzert** [comment]
Hey George,
I added revoke-certificate and thus needed to export certificates as well - I added that code, but did not yet test it in any way.
So if you are feeling lucky, you might go for beta4 ;)

**Comment by GeorgeSchiro** [comment]
Does beta4 include your recent changes to the "AcmeStatePaths" class?

**Comment by glatzert** [comment]
Beta4 includes all bugfixes (along AcmeStatePaths) and following improvements:

- String to State conversion
- String to DNS-Identifier conversion
- Automatically create an certificatekey in Complete-Order (will be stored as Order.key.xml)
- Store the certificate in Export-AcmeCertificate (will be stored as Order.pem) to allow
- Revoke-AcmeCertificate
- Set-AcmeAccount -DeactivateAccount

**Comment by GeorgeSchiro** [comment]
I removed the previous ""C:\Program Files\WindowsPowerShell\Modules\ACME-PS" folder, then did this:

    Install-Module -Name ACME-PS -AllowPrerelease

This is what I see in beta4 ("AcmeStatePaths" class):

        $this.ServiceDirectory = "$($this.BasePath)/ServiceDirectory.xml";
        $this.Nonce = "$($this.BasePath)/NextNonce.txt";
        $this.AccountKey = "$($this.BasePath)AccountKey.xml";
        $this.Account = "$($this.BasePath)Account.xml";

        $this.OrderList = "$($this.BasePath)Orders/OrderList.txt"
        $this.Order = "$($this.BasePath)Orders/Order-[hash].xml";

**Comment by glatzert** [comment]
That's the old code :/

Am 30.01.2020 20:14 schrieb George Schiro <notifications@github.com>:

I removed the previous ""C:\Program Files\WindowsPowerShell\Modules\ACME-PS" folder, then did this:

Install-Module -Name ACME-PS -AllowPrerelease


This is what I see in beta4 ("AcmeStatePaths" class):

    $this.ServiceDirectory = "$($this.BasePath)/ServiceDirectory.xml";
    $this.Nonce = "$($this.BasePath)/NextNonce.txt";
    $this.AccountKey = "$($this.BasePath)AccountKey.xml";
    $this.Account = "$($this.BasePath)Account.xml";

    $this.OrderList = "$($this.BasePath)Orders/OrderList.txt"
    $this.Order = "$($this.BasePath)Orders/Order-[hash].xml";

**Comment by glatzert** [comment]
As I said before _beta5_ includes ... ;)

> Beta4 includes all bugfixes (along AcmeStatePaths) and following improvements:
> 
> * String to State conversion
> * String to DNS-Identifier conversion
> * Automatically create an certificatekey in Complete-Order (will be stored as Order.key.xml)
> * Store the certificate in Export-AcmeCertificate (will be stored as Order.pem) to allow
> * Revoke-AcmeCertificate
> * Set-AcmeAccount -DeactivateAccount

**Comment by GeorgeSchiro** [comment]
Ok, got beta5 (Thank you Thomas). Everything looked good until this:

    Using Module "C:\Users\admin\Desktop\tmp\ACME-PS"

    $identifiers = Import-Clixml "C:\Users\admin\Desktop\tmp\AcmeState\identifiers.xml"
    $order = Find-ACMEOrder "C:\Users\admin\Desktop\tmp\AcmeState" -Identifiers $identifiers
    $certKey = Import-ACMECertificateKey -Path "C:\Users\admin\Desktop\tmp\AcmeState\cert.key.xml"
    Export-ACMECertificate "C:\Users\admin\Desktop\tmp\AcmeState" -Order $order -CertificateKey $certKey -Path "C:\Users\admin\Desktop\tmp\test.pfx"

I confirmed $identifiers, $order & $certKey all have expected content (ie. not null). Yet here's the error:

    Export-ACMECertificate : Exception calling ".ctor" with "1" argument(s): "Value cannot be null.
    Parameter name: cert"
    At line:1 char:1
    + Export-ACMECertificate "C:\Users\admin\Desktop\tmp\AcmeState" -Order  ...
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [Export-ACMECertificate], MethodInvocationException
        + FullyQualifiedErrorId : ArgumentNullException,Export-ACMECertificate

**Comment by glatzert** [comment]
OKay - good to know it works up to that point.
The error occures, because I wrote `$null -ne $certificate` when I should have written `$null -eq $certificate`. I'll fix that. Thanks for your time.

**Comment by GeorgeSchiro** [comment]
NP. It's the least I can do Thomas. Thank YOU.

**Comment by glatzert** [comment]
All done. 1.1.3 is published.
