### ISSUE TITLE
AcmeException Doesn't Exist

### ISSUE THREAD

**Issue by GeorgeSchiro** [PKISharp/ACMESharpCore-PowerShell#58]
To get proper feedback from LE (eg. "rate limit reached"), I needed to do this:

from:

    throw [AcmeException]::new($respone.ErrorMessage, $response)

to:

    throw [AcmeHttpException]::new($response.ErrorMessage, $response)

and

from ("$this.Message" is read-only):

    class AcmeHttpException : System.Exception {
        AcmeHttpException([string]$_message, [AcmeHttpResponse]$_response) {
            $this.Message = $_message;
            $this.Response = $_response;
        }

        [AcmeHttpResponse]$Response;
    }

to:

    class AcmeHttpException : System.Exception {
        AcmeHttpException([string]$_message, [AcmeHttpResponse]$_response) {
            throw "$($_message)`n$($_response.Content)"
        }
    }

**Comment by glatzert** [comment]
Your fix hides the details - essentially (if you want to do something fancy), you'll need access to the Error-Details, which are available via $exception.Response.Content.
I created the neccessary fix and will provide them via the gallery in some days (there are more minor problems I, which should be addressed)

**Comment by GeorgeSchiro** [comment]
IMHO, the default behavior should be what is most helpful. Here's what I see with the "1.1.4" version of "AcmeHttpException":

    New-ACMEOrder "C:\Users\admin\Desktop\tmp\AcmeState" -Identifiers $SanList

    At C:\Users\admin\Desktop\tmp\ACME-PS\1.1.4\ACME-PS.psm1:1395 char:13
    +             throw [AcmeHttpException]::new($respone.ErrorMessage, $re ...
    +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : OperationStopped: (:) [], AcmeHttpException
        + FullyQualifiedErrorId :

As you can see, no helpful feedback.

Here's what I see with the version of "AcmeHttpException" I posted above (2/1 comment)

    New-ACMEOrder "C:\Users\admin\Desktop\tmp\AcmeState" -Identifiers $SanList

    @{type=urn:ietf:params:acme:error:rateLimited; detail=Error creating new order :: too many certificates already issued for exact set of domains: ...: see
    https://letsencrypt.org/docs/rate-limits/; status=429}
    At C:\Users\admin\Desktop\tmp\ACME-PS\1.1.4\ACME-PS.psm1:523 char:9
    +         throw "$($_message)`n$($_response.Content)"
    +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : OperationStopped: (
    @{type=urn:iet...s/; status=429}:String) [], RuntimeException
        + FullyQualifiedErrorId :
        @{type=urn:ietf:params:acme:error:rateLimited; detail=Error creating new order :: too many certificates already issued for exact set of domains: ...: see https://le
    tsencrypt.org/docs/rate-limits/; status=429}

Here's what a troubleshooter needs to quickly understand and resolve the issue:

    error:rateLimited; detail=Error creating new order :: too many certificates already issued

I think the "1.1.4" version is hiding details.

**Comment by glatzert** [comment]
I see the problem.

Nevertheless throwing the error without the `$response` being attached to the object is good for "interactive", but not for automated environments.
You could for example automatically wait, if you got rateLimited, but that means, you have to access the error-type of the response.

I'm using throw for that, since I want to ensure the pipeline breaking.

So technically I need an Exception, which will stop the pipeline, can be handled with `try {} catch {}` AND will print a useful error message.

**Comment by glatzert** [comment]
So - NORMALLY - an Exception.Message will be displayed as first line.
But I messed up `$response.ErrorMessage`, which simply does not exist - it's more or less a typo.

To conclude: I need to use `$response.ErrorMessage` as Message and I will add `$response.Content.Details` to the message, if it exists.

That'll make it readable for humans and usable for machines.

**Comment by glatzert** [comment]
Fixed it, and will deploy it as 1.1.5 between monday and wednesday
