### ISSUE TITLE
A Little More Feedback Would Be Nice

### ISSUE THREAD

**Issue by GeorgeSchiro** [PKISharp/ACMESharpCore-PowerShell#59]
These commands offer feedback upon successful completion:

    Complete-ACMEChallenge
    Export-ACMECertificate (in the form of a PFX file)
    Get-ACMEServiceDirectory
    New-ACMEAccountKey
    New-ACMEOrder
    New-ACMEState
    Update-ACMEOrder

These don't:

    Complete-ACMEOrder
    Get-ACMEAuthorization
    New-ACMEAccount
    New-ACMENonce

It would be nice if at least "Complete-ACMEOrder" offered some feedback.

Thank you again for all of your great effort Thomas. The tool is excellent.

**Comment by glatzert** [comment]
You can use the `-PassThru` switch (most of the commands implement that switch), which will send the results to the output as well.
Get-AcmeAuthorization should already return something (else `$auth = Get-AcmeAuth` would not work).
Perhaps, it would be an option to leverage PowerShells Information-Stream, but you need to opt-in to get the outputs of that stream.

**Comment by GeorgeSchiro** [comment]
Got it. Didn't get the purpose of "-PassThru". Do now. Thanks!
