### ISSUE TITLE
PEM File in AcmeState

### ISSUE THREAD

**Issue by GeorgeSchiro** [PKISharp/ACMESharpCore-PowerShell#63]
We've completed a full regression test going from "1.1.0" to "1.1.4". Looks good Thomas! We are looking forward to a final test of your soon-to-be released "1.1.5" version of "AcmeHttpException".

While reviewing "AcmeState" we noticed something new, a PEM file that looks like:

    .\Orders\Order-sPiHXRi3mrAaVVlnaiBlMN27Pe6qXz-ldnXhh0Ixgao.pem

We would prefer not to discard "AcmeState" after each "ACME-PS" run. We use it to diagnose issues, if any. We cleanup the previous "AcmeState" during the next run. So sensitive data can't linger there.

Since "Export-ACMECertificate" explicitly exports to PFX format, can you cleanup the PEM file in the "Orders" folder after "Export-ACMECertificate" completes?

**Comment by glatzert** [comment]
The pem is needed for revocation. Currently I'm unsure, if there's an option to regain the certificate from an "older" order. But it's not sensitive data - it's the public keys of the issued certficiate.

Nevertheless, I'll include a switch into Export-ACMECertificate to allow opting-out.

**Comment by GeorgeSchiro** [comment]
Good to know there's no private key in there. Thanks!

**Comment by glatzert** [comment]
Solved in v1.1.5

**Comment by GeorgeSchiro** [comment]
Thanks as always Thomas!
