### ISSUE TITLE
Az module cmdlets fail when ACME-PS module loaded

### ISSUE THREAD

**Issue by sergethedev17** [PKISharp/ACMESharpCore-PowerShell#66]
I have an Azure Automation runbook that uses **ACME-PS** and **Az.Storage** modules.
When ACME-PS module (1.1.5) is loaded, cmdlets from Az.Storage (1.12.0) throw exceptions.

## Runbook script
```powershell
$ErrorActionPreference = 'Stop'

"Loaded modules:"
Get-Module

$connectionName = "AzureRunAsConnection"

try
{
    # Get the connection "AzureRunAsConnection "

    $servicePrincipalConnection = Get-AutomationConnection -Name $connectionName

    "Logging in to Azure..."
    $connectionResult =  Connect-AzAccount -Tenant $servicePrincipalConnection.TenantID `
                             -ApplicationId $servicePrincipalConnection.ApplicationID   `
                             -CertificateThumbprint $servicePrincipalConnection.CertificateThumbprint `
                             -ServicePrincipal
    "Logged in."

}
catch {
    if (!$servicePrincipalConnection)
    {
        $ErrorMessage = "Connection $connectionName not found."
        throw $ErrorMessage
    } else{
        Write-Error -Message $_.Exception
        throw $_.Exception
    }
}


$stateDir = "$($PWD.Path)\acmestate-LetsEncrypt-Staging"

# Ensure state directory exists
if(!(Test-Path $stateDir -t Container)){
    New-Item -ItemType Directory -Force -Path $stateDir | Out-Null
}

if(Get-Module 'ACME-PS'){"Module ACME-PS is loaded"}else{"Module ACME-PS is not loaded"}

"New-ACMEState:"
# *** Comment/Uncomment the following line to trigger crashes
# *** Note that once uncommented, the crashes will recur even AFTER the line is commented out again
$state = New-ACMEState -Path $stateDir

if(Get-Module 'ACME-PS'){"Module ACME-PS is loaded"}else{"Module ACME-PS is not loaded"}

if(Get-Module 'ACME-PS'){
    # This line does not appear to have any effect
    "Unloading Removing module ACME-PS"
    Remove-Module 'ACME-PS' -Force -Verbose
}
if(Get-Module 'ACME-PS'){"Module ACME-PS is loaded"}else{"Module ACME-PS is not loaded"}

try{
    "Get-AzContext: "
    $AzStorageProfile = Get-AzContext -ListAvailable | ? { $_.Subscription.Name -eq 'Pay-As-You-Go' }
    $AzStorageProfile

    "Get-AzStorageAccount: "
    $AzStorageAcc = Get-AzStorageAccount -Name '__REDACTED_STORAGE_ACCOUNT_NAME__' -ResourceGroupName '__REDACTED_STORAGE_ACCOUNT_RG_NAME__' -DefaultProfile $AzStorageProfile
    $AzStorageAcc
}
catch [System.Management.Automation.CommandNotFoundException]{
    "Caught exception!"
    $_ | Select-Object -Property *
}
```

## Exception details
```
System.Management.Automation.CommandNotFoundException: The 'Get-AzStorageAccount' command was found in the module 'Az.Storage', but the module could not be loaded. For more information, run 'Import-Module Az.Storage'. ---> System.Management.Automation.CmdletInvocationException: The following error occurred while loading the extended type data file: 
Microsoft.PowerShell, C:\Modules\User\ACME-PS\Types.ps1xml(8) : Error in type "AcmeState": The "Type" node must have "Members", "TypeConverters", or "TypeAdapters".
Microsoft.PowerShell, C:\Modules\User\ACME-PS\Types.ps1xml(11) : Error: Unable to find type [AcmeObjectConverter].
Microsoft.PowerShell, C:\Modules\User\ACME-PS\Types.ps1xml(2) : Error in type "AcmeIdentifier": The "Type" node must have "Members", "TypeConverters", or "TypeAdapters".
Microsoft.PowerShell, C:\Modules\User\ACME-PS\Types.ps1xml(5) : Error: Unable to find type [AcmeObjectConverter].
 ---> System.Management.Automation.RuntimeException: The following error occurred while loading the extended type data file: 
Microsoft.PowerShell, C:\Modules\User\ACME-PS\Types.ps1xml(8) : Error in type "AcmeState": The "Type" node must have "Members", "TypeConverters", or "TypeAdapters".
Microsoft.PowerShell, C:\Modules\User\ACME-PS\Types.ps1xml(11) : Error: Unable to find type [AcmeObjectConverter].
Microsoft.PowerShell, C:\Modules\User\ACME-PS\Types.ps1xml(2) : Error in type "AcmeIdentifier": The "Type" node must have "Members", "TypeConverters", or "TypeAdapters".
Microsoft.PowerShell, C:\Modules\User\ACME-PS\Types.ps1xml(5) : Error: Unable to find type [AcmeObjectConverter].

   at System.Management.Automation.Runspaces.FormatAndTypeDataHelper.ThrowExceptionOnError(String errorId, Collection`1 independentErrors, Collection`1 PSSnapinFilesCollection, RunspaceConfigurationCategory category)
   at System.Management.Automation.Runspaces.RunspaceConfigurationEntryCollection`1.Update(Boolean force)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors)
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T]()
   at System.Management.Automation.CommandDiscovery.AutoloadSpecifiedModule(String moduleName, ExecutionContext context, SessionStateEntryVisibility visibility, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Management.Automation.CommandDiscovery.TryModuleAutoDiscovery(String commandName, ExecutionContext context, String originalCommandName, CommandOrigin commandOrigin, SearchResolutionOptions searchResolutionOptions, CommandTypes commandTypes, Exception& lastError)
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

```

## List of modules installed in automation account
|Name|Last modified|Status|Version|
|---|---|---|---|
ACME-PS|18/02/2020, 11:27 am|Available|1.1.5
AuditPolicyDsc|27/02/2020, 8:07 pm|Available|1.1.0.0
Az.Accounts|02/03/2020, 9:57 am|Available|1.7.2
Az.Automation|02/03/2020, 9:59 am|Available|1.3.6
Az.Dns|19/02/2020, 3:51 pm|Available|1.1.2
Az.Resources|02/03/2020, 9:59 am|Available|1.11.0
Az.Sql|02/03/2020, 9:59 am|Available|2.3.0
Az.Storage|18/02/2020, 10:52 am|Available|1.12.0
Azure|25/02/2020, 10:44 am|Available|5.3.0
Azure.Storage|25/02/2020, 10:41 am|Available|4.6.1
AzureRM.Automation|25/02/2020, 10:41 am|Available|6.1.1
AzureRM.Compute|25/02/2020, 10:41 am|Available|5.9.1
AzureRM.Profile|25/02/2020, 10:39 am|Available|5.8.3
AzureRM.Resources|25/02/2020, 10:41 am|Available|6.7.3
AzureRM.Sql|25/02/2020, 10:41 am|Available|4.12.1
AzureRM.Storage|25/02/2020, 10:43 am|Available|5.2.0
ComputerManagementDsc|27/02/2020, 8:06 pm|Available|5.0.0.0
GPRegistryPolicyParser|27/02/2020, 8:07 pm|Available|0.2
REDACTED_PRIVATE_MODULE|02/03/2020, 11:25 am|Available|1.0.0.2
Microsoft.PowerShell.Core|27/02/2020, 7:55 pm|Available|0.0
Microsoft.PowerShell.Diagnostics|27/02/2020, 7:55 pm|Available|Microsoft.PowerShell.Management|27/02/2020, 7:55 pm|Available|Microsoft.PowerShell.Security|27/02/2020, 7:56 pm|Available|Microsoft.PowerShell.Utility|27/02/2020, 7:56 pm|Available|Microsoft.WSMan.Management|27/02/2020, 7:57 pm|Available|Orchestrator.AssetManagement.Cmdlets|27/02/2020, 8:09 pm|Available|1.0
PSDscResources|27/02/2020, 8:08 pm|Available|2.9.0.0
SecurityPolicyDsc|27/02/2020, 8:07 pm|Available|2.1.0.0
StateConfigCompositeResources|27/02/2020, 8:09 pm|Available|1.0
xDSCDomainjoin|27/02/2020, 8:06 pm|Available|1.1
xPowerShellExecutionPolicy|27/02/2020, 8:05 pm|Available|1.1.0.0
xRemoteDesktopAdmin|27/02/2020, 8:06 pm|Available|1.1.0.0

**Comment by glatzert** [comment]
I've seen this error before, when I first introduced the automatic type converters, which were not very happy about being used with Powershell-classes.

Can you try to explicitly load the ACME-PS module by calling import-module as a workaround?
I don't have a runbook available to do the necessary tests currently.

Am 02.03.2020 04:41 schrieb Serge <notifications@github.com>:

I have an Azure Automation runbook that uses ACME-PS and Az.Storage modules.
When ACME-PS module (1.1.5) is loaded, cmdlets from Az.Storage (1.12.0) throw exceptions.

Runbook script

$ErrorActionPreference = 'Stop'

"Loaded modules:"
Get-Module

$connectionName = "AzureRunAsConnection"

try
{
    # Get the connection "AzureRunAsConnection "

    $servicePrincipalConnection = Get-AutomationConnection -Name $connectionName

    "Logging in to Azure..."
    $connectionResult =  Connect-AzAccount -Tenant $servicePrincipalConnection.TenantID `
                             -ApplicationId $servicePrincipalConnection.ApplicationID   `
                             -CertificateThumbprint $servicePrincipalConnection.CertificateThumbprint `
                             -ServicePrincipal
    "Logged in."

}
catch {
    if (!$servicePrincipalConnection)
    {
        $ErrorMessage = "Connection $connectionName not found."
        throw $ErrorMessage
    } else{
        Write-Error -Message $_.Exception
        throw $_.Exception
    }
}


$stateDir = "$($PWD.Path)\acmestate-LetsEncrypt-Staging"

# Ensure state directory exists
if(!(Test-Path $stateDir -t Container)){
    New-Item -ItemType Directory -Force -Path $stateDir | Out-Null
}

if(Get-Module 'ACME-PS'){"Module ACME-PS is loaded"}else{"Module ACME-PS is not loaded"}

"New-ACMEState:"
# *** Comment/Uncomment the following line to trigger crashes
# *** Note that once uncommented, the crashes will recur even AFTER the line is commented out again
$state = New-ACMEState -Path $stateDir

if(Get-Module 'ACME-PS'){"Module ACME-PS is loaded"}else{"Module ACME-PS is not loaded"}

if(Get-Module 'ACME-PS'){
    # This line does not appear to have any effect
    "Unloading Removing module ACME-PS"
    Remove-Module 'ACME-PS' -Force -Verbose
}
if(Get-Module 'ACME-PS'){"Module ACME-PS is loaded"}else{"Module ACME-PS is not loaded"}

try{
    "Get-AzContext: "
    $AzStorageProfile = Get-AzContext -ListAvailable | ? { $_.Subscription.Name -eq 'Pay-As-You-Go' }
    $AzStorageProfile

    "Get-AzStorageAccount: "
    $AzStorageAcc = Get-AzStorageAccount -Name '__REDACTED_STORAGE_ACCOUNT_NAME__' -ResourceGroupName '__REDACTED_STORAGE_ACCOUNT_RG_NAME__' -DefaultProfile $AzStorageProfile
    $AzStorageAcc
}
catch [System.Management.Automation.CommandNotFoundException]{
    "Caught exception!"
    $_ | Select-Object -Property *
}

Exception details

System.Management.Automation.CommandNotFoundException: The 'Get-AzStorageAccount' command was found in the module 'Az.Storage', but the module could not be loaded. For more information, run 'Import-Module Az.Storage'. ---> System.Management.Automation.CmdletInvocationException: The following error occurred while loading the extended type data file:
Microsoft.PowerShell, C:\Modules\User\ACME-PS\Types.ps1xml(8) : Error in type "AcmeState": The "Type" node must have "Members", "TypeConverters", or "TypeAdapters".
Microsoft.PowerShell, C:\Modules\User\ACME-PS\Types.ps1xml(11) : Error: Unable to find type [AcmeObjectConverter].
Microsoft.PowerShell, C:\Modules\User\ACME-PS\Types.ps1xml(2) : Error in type "AcmeIdentifier": The "Type" node must have "Members", "TypeConverters", or "TypeAdapters".
Microsoft.PowerShell, C:\Modules\User\ACME-PS\Types.ps1xml(5) : Error: Unable to find type [AcmeObjectConverter].
 ---> System.Management.Automation.RuntimeException: The following error occurred while loading the extended type data file:
Microsoft.PowerShell, C:\Modules\User\ACME-PS\Types.ps1xml(8) : Error in type "AcmeState": The "Type" node must have "Members", "TypeConverters", or "TypeAdapters".
Microsoft.PowerShell, C:\Modules\User\ACME-PS\Types.ps1xml(11) : Error: Unable to find type [AcmeObjectConverter].
Microsoft.PowerShell, C:\Modules\User\ACME-PS\Types.ps1xml(2) : Error in type "AcmeIdentifier": The "Type" node must have "Members", "TypeConverters", or "TypeAdapters".
Microsoft.PowerShell, C:\Modules\User\ACME-PS\Types.ps1xml(5) : Error: Unable to find type [AcmeObjectConverter].

   at System.Management.Automation.Runspaces.FormatAndTypeDataHelper.ThrowExceptionOnError(String errorId, Collection`1 independentErrors, Collection`1 PSSnapinFilesCollection, RunspaceConfigurationCategory category)
   at System.Management.Automation.Runspaces.RunspaceConfigurationEntryCollection`1.Update(Boolean force)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors)
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T]()
   at System.Management.Automation.CommandDiscovery.AutoloadSpecifiedModule(String moduleName, ExecutionContext context, SessionStateEntryVisibility visibility, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Management.Automation.CommandDiscovery.TryModuleAutoDiscovery(String commandName, ExecutionContext context, String originalCommandName, CommandOrigin commandOrigin, SearchResolutionOptions searchResolutionOptions, CommandTypes commandTypes, Exception& lastError)
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)



List of modules installed in automation account
Name    Last modified   Status  Version
ACME-PS 18/02/2020, 11:27 am    Available       1.1.5
AuditPolicyDsc  27/02/2020, 8:07 pm     Available       1.1.0.0
Az.Accounts     02/03/2020, 9:57 am     Available       1.7.2
Az.Automation   02/03/2020, 9:59 am     Available       1.3.6
Az.Dns  19/02/2020, 3:51 pm     Available       1.1.2
Az.Resources    02/03/2020, 9:59 am     Available       1.11.0
Az.Sql  02/03/2020, 9:59 am     Available       2.3.0
Az.Storage      18/02/2020, 10:52 am    Available       1.12.0
Azure   25/02/2020, 10:44 am    Available       5.3.0
Azure.Storage   25/02/2020, 10:41 am    Available       4.6.1
AzureRM.Automation      25/02/2020, 10:41 am    Available       6.1.1
AzureRM.Compute 25/02/2020, 10:41 am    Available       5.9.1
AzureRM.Profile 25/02/2020, 10:39 am    Available       5.8.3
AzureRM.Resources       25/02/2020, 10:41 am    Available       6.7.3
AzureRM.Sql     25/02/2020, 10:41 am    Available       4.12.1
AzureRM.Storage 25/02/2020, 10:43 am    Available       5.2.0
ComputerManagementDsc   27/02/2020, 8:06 pm     Available       5.0.0.0
GPRegistryPolicyParser  27/02/2020, 8:07 pm     Available       0.2
REDACTED_PRIVATE_MODULE 02/03/2020, 11:25 am    Available       1.0.0.2
Microsoft.PowerShell.Core       27/02/2020, 7:55 pm     Available       0.0
Microsoft.PowerShell.Diagnostics        27/02/2020, 7:55 pm     Available       Microsoft.PowerShell.Management
PSDscResources  27/02/2020, 8:08 pm     Available       2.9.0.0
SecurityPolicyDsc       27/02/2020, 8:07 pm     Available       2.1.0.0
StateConfigCompositeResources   27/02/2020, 8:09 pm     Available       1.0
xDSCDomainjoin  27/02/2020, 8:06 pm     Available       1.1
xPowerShellExecutionPolicy      27/02/2020, 8:05 pm     Available       1.1.0.0
xRemoteDesktopAdmin     27/02/2020, 8:06 pm     Available       1.1.0.0

**Comment by sergethedev17** [comment]
I tried explicitly loading the ACME-PS Module (eg `Import-Module 'ACME-PS' -Force`). This did not help.

There are 2 other relevant issues:
1. Removing the ACME-PS module (eg `Remove-Module 'ACME-PS'`) after it is used does not immediately resolve the issue.
2. Commenting out all ACME-xxx cmdlets does not immediately resolve the issue.

**Steps to reproduce:**
1. Execute unmodified *Runbook script*, as per my first comment.
2. Edit script and commend out `$state = New-ACMEState -Path $stateDir` line.
3. Publish updated script.
4. Execute updated script.

**Excepted behaviour:**
Script throws exception at step 1.
Script does not throw exception at step 4.

**Actual behaviour:**
Script throws exception at both steps 1 and 4.

Note however that above cannot be always reproduced. Sometimes it is necessary to follow the **Steps to reproduce** two or more times.

**Comment by glatzert** [comment]
My knowledge about Runbooks is very limited, nevertheless I can tell you, that the error occurs during module load of ACME-PS (that's the only location the type xml file is used).
Removing and adding the module again might do harm here, since ACME-PS makes heavy usage of powershell classes, which are - to me knowledge - not completely cleaned up during removal of a module. So if you once loaded the module in your powershell session, you should neither remove it nor import it again with using -force - that both will make an possibly undefined state for the classes.

**Comment by fmartin1987** [comment]
Hi, I was wondering if this issue is still pending because I am going exactly through the same problems...

I have published a runbook in an Azure automation account in which two different parts are being executed:
1. First one, it connects to LetsEncrypt and obtains a challenge token and its data content (Got from [here](https://github.com/intelequia/letsencrypt-aw/blob/master/letsencryptaw_v2.ps1)).

`# Create a state object and save it to the harddrive
    $state = New-ACMEState -Path $env:TEMP
    $serviceName = 'LetsEncrypt'

    # Fetch the service directory and save it in the state
    Get-ACMEServiceDirectory $state -ServiceName $serviceName -PassThru;

    # Get the first anti-replay nonce
    New-ACMENonce $state;

    # Create an account key. The state will make sure it's stored.
    New-ACMEAccountKey $state -PassThru;

    # Register the account key with the acme service. The account key will automatically be read from the state
    New-ACMEAccount $state -EmailAddresses $EmailAddress -AcceptTOS;

    # Load an state object to have service directory and account keys available
    $state = Get-ACMEState -Path $env:TEMP;

    # It might be neccessary to acquire a new nonce, so we'll just do it for the sake of the example.
    New-ACMENonce $state -PassThru;

    # Create the identifier for the DNS name
    $identifier = New-ACMEIdentifier $domain;

    # Create the order object at the ACME service.
    $order = New-ACMEOrder $state -Identifiers $identifier;

    # Fetch the authorizations for that order
    $authZ = Get-ACMEAuthorization -State $state -Order $order;

    # Select a challenge to fullfill
    $challenge = Get-ACMEChallenge $state $authZ "http-01";

    # Inspect the challenge data
    $challenge.Data;`

2. Then, another function tries to write that token file (with that content) in a storage account

`function write_challenge_token($token, $tokenData) {
    try
    {
        # Create new file
        New-Item -ItemType File -Name "$token"

        # Insert data into it
        Set-Content -Path "$token" -Value "$tokenData" -NoNewline;

        # Set blob path
        $blobName = ".well-known/acme-challenge/" + "$token"

        # Get key to storage account
        $acctKey = (Get-AzStorageAccountKey -Name $storageName -ResourceGroupName $STResourceGroupName).Value[0]
        
        # Map to the reports BLOB context
        $storageContext = New-AzStorageContext -StorageAccountName $storageName -StorageAccountKey $acctKey
        
        # Copy the file to the storage account
        Set-AzStorageBlobContent -File "$token" -Container "public" -BlobType "Block" -Blob $blobName -Context $storageContext -Force -Verbose
    }
    catch {
        Write-Error -Message $_.Exception
        throw $_.Exception
    }
}`

Later more stuff should be done but that is out of the scope. The thing is:

- If I execute only the first part (the one that makes usage of ACME-PS) the powershell script ends ok.

- If I skip the first part and I invoke the write_challenge_token function (uses Az.Storage) (with hardcoded strings for both parameters (simulating that letsencrypt would have return them)), it also works fine.

- However, if I execute both parts and I try to call the write function passing it the token and tokenData properly obtained from Letsencrypt, then powershell complains about the modules importation:

`Type        : http-01
Token       : HHuku4LO6C5QdLd7EPsAnwqgdvA_mLRdIpSBdgdee-M
Filename    : HHuku4LO6C5QdLd7EPsAnwqgdvA_mLRdIpSBdgdee-M
RelativeUrl : /.well-known/acme-challenge/HHuku4LO6C5QdLd7EPsAnwqgdvA_mLRdIpSBdgdee-M
AbsoluteUrl : uatapidockers.dev.bestinver.es/.well-known/acme-challenge/HHuku4LO6C5QdLd7EPsAnwqgdvA_mLRdIpSBdgdee-M
Content     : HHuku4LO6C5QdLd7EPsAnwqgdvA_mLRdIpSBdgdee-M.LtDDLv4YxLmEHubnL3RMJjT4w4UMTenG-OYoiOX_Ckw
Get-AzStorageAccount : The 'Get-AzStorageAccount' command was found in the module 'Az.Storage', but the module could 
not be loaded. For more information, run 'Import-Module Az.Storage'.
At line:86 char:19
+ $storageAccount = Get-AzStorageAccount -ResourceGroupName $STResource ...
+                   ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AzStorageAccount:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
 
Set-AzureStorageBlobContent : The 'Set-AzureStorageBlobContent' command was found in the module 'Azure.Storage', but 
the module could not be loaded. For more information, run 'Import-Module Azure.Storage'.
At line:93 char:1
+ Set-AzureStorageBlobContent -File $fileName -Container "public" -Cont ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Set-AzureStorageBlobContent:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule`

Please, any help would be appreciated.
Thanks in advance,
Best Regards,
Fernando.

**Comment by glatzert** [comment]
I really have litte idea about runbooks, but it seems you'll need to check if your modules are loaded (Get-Module) and if not load them.

Reloading a module (e.g. `ipmo ACME-PS -force`) _will_ make problems with ACME-PS, if you do it in the same powershell session.

**Comment by natelowry** [comment]
I'm also running into this after upgrading from `ACMESharp`.  I'm running the powershell script from some .NET code, but haven't run into issues like this in the past.  How can I help debug?

**Comment by glatzert** [comment]
Can you outline how you initialize and use the script from your integrated shell?
How's module loading done? How's the lifetime of the shell instance?
Do you reload the module at any time?
What exactly is the error message?

**Comment by andyghc** [comment]
Just a note, I had all sorts of modules issues with my automation account and ACME-PS.  I did get it to work by starting fresh with a new automation account, and importing the relevant az. modules.  In my script I also manually import modules for use:

Import-Module Az.Accounts
Import-Module Az.Automation
Import-Module Az.Storage
Import-Module ACME-PS

Seems to work okay for me.

**Comment by natelowry** [comment]
I actually took a different approach for LE which I got working, so didn't end up figure out what was going on.  Sorry I can't be more helpful, but I'll try.

> Can you outline how you initialize and use the script from your integrated shell?

It's a .NET 4.6.1 exe running as a Windows service.  Loaded like so:
```
var runspace = RunspaceFactory.CreateRunspace();
runspace.Open();
var pipeline = runspace.CreatePipeline();
pipeline.Commands.Add(new Command("foo/bar.ps1");
pipeline.Invoke();
```

> How's module loading done? How's the lifetime of the shell instance?

I tried a few different ways with installing it for `AllUsers` or `CurrentUser` ahead of time and as a part of the script.  With and without `AllowClobber`

> Do you reload the module at any time?

I think so and it sounds like maybe that's the problem? 

> What exactly is the error message?

My error message was pretty much the same as above (sry I don't have the exact text)

**Comment by GitMaggie** [comment]
I had a similar case with this issue and now it's resolved .Hope it helps .
Root Cause: 
- Import fails for Az.Storage module after ACME-PS module is imported. The reason behind such behavior is the environment in which Automation service runs powershell scripts is not publicly available PowerShell. Automation jobs run in a special secure environment.
Resolution :
- To use it in Automaiton runbook, we need  import Az.Storage  module explicitly . The import statement should be before importing/running cmdlet from ACME-PS module.

```
Import-Module 'Az.Storage'
"Module Az.Storage is loaded"
...
$state = New-ACMEState -Path $PWD.Path
```

**Comment by fmartin1987** [comment]
I agree with @GitMaggie and as @glatzert suggested too, this (at least in my case) was a modules importation issue.

After load Az.Storage explicitly, it worked fine.

Thanks to all involved.

**Comment by glatzert** [comment]
Since I still do not have such an account, I'll not be able to verify that behaviour.
Nevertheless I added some information to the runbook example (via https://github.com/PKISharp/ACMESharpCore-PowerShell/commit/29282827b554306c01b5bd7bc83d38197a4b0dc2).

In the case anyone wants to add something, either use this issue or feel free to provide a PR.

**Comment by glatzert** [comment]
Also I implemented a small fix for the type-conversion (e.g string to state and string to identifier), which might also impact this issue and will be available in the next version somewhen this week.
